@echo off
chcp 65001 >nul
setlocal
title Research Agent 本地一键启动

cd /d "%~dp0"
set "ROOT=%~dp0"

REM ============================================================
REM  可配置项：若端口冲突，只改这里即可（前端 .env.local 会同步更新）
REM ============================================================
set "BACKEND_PORT=8010"
set "FRONTEND_PORT=3001"

echo ============================================
echo   Research Agent 本地启动（非 Docker）
echo   后端 :%BACKEND_PORT%  ^|  前端 :%FRONTEND_PORT%
echo ============================================
echo.

REM ---------- 1) 后端依赖（虚拟环境位于项目根 .venv） ----------
if exist ".venv\Scripts\python.exe" (
  echo [1/5] 后端虚拟环境 .venv 已存在，跳过依赖安装。
) else (
  echo [1/5] 未找到 .venv，正在创建虚拟环境并安装依赖（首次较慢）...
  python -m venv .venv
  if errorlevel 1 (
    echo [错误] 创建虚拟环境失败。请确认已安装 Python 3.12+ 并加入 PATH。
    pause & exit /b 1
  )
  ".venv\Scripts\python.exe" -m pip install --upgrade pip
  ".venv\Scripts\python.exe" -m pip install -e .
  if errorlevel 1 (
    echo [错误] 后端依赖安装失败。
    pause & exit /b 1
  )
)

REM ---------- 2) 后端配置 ----------
if exist ".env" (
  echo [2/5] 后端 .env 已就绪。
) else (
  echo [2/5] 未找到 .env，已从 .env.example 复制一份。
  copy ".env.example" ".env" >nul
  echo        请填写 OPENAI_API_KEY / TAVILY_API_KEY 后重新运行本脚本。
)

REM ---------- 3) 前端配置：让前端指向后端端口 ----------
(
  echo # Auto-generated by start.bat: backend URL used by the frontend.
  echo NEXT_PUBLIC_GPTR_API_URL=http://localhost:%BACKEND_PORT%
) > "frontend\nextjs\.env.local"
echo [3/5] 已写入 frontend\nextjs\.env.local ^(NEXT_PUBLIC_GPTR_API_URL=http://localhost:%BACKEND_PORT%^)

REM ---------- 4) 启动后端（必须在项目根目录运行，否则 /outputs 静态目录会 404） ----------
echo [4/5] 启动后端 http://127.0.0.1:%BACKEND_PORT% ...
set "PORT=%BACKEND_PORT%"
start "Research Agent backend :%BACKEND_PORT%" cmd /k ".venv\Scripts\python.exe main.py"

REM ---------- 5) 前端依赖 + 启动 ----------
if exist "frontend\nextjs\node_modules" (
  echo [5/5] 前端依赖已存在，直接启动 http://localhost:%FRONTEND_PORT% ...
) else (
  echo [5/5] 未找到 frontend\nextjs\node_modules，正在安装依赖（首次较慢）...
  pushd "frontend\nextjs"
  call npm install --legacy-peer-deps
  if errorlevel 1 (
    echo [错误] npm install 失败。请确认已安装 Node.js 18+。
    popd & pause & exit /b 1
  )
  popd
)
start "Research Agent frontend :%FRONTEND_PORT%" /d "%ROOT%frontend\nextjs" cmd /k "npm run dev -- -p %FRONTEND_PORT%"

echo.
echo 已启动完成：
echo   后端 http://127.0.0.1:%BACKEND_PORT%
echo   前端 http://localhost:%FRONTEND_PORT%   ^(浏览器打开这个^)
echo.
echo 关闭服务：直接关掉弹出的两个命令行窗口即可。
echo.
pause
endlocal